### ISSUE TITLE
【报错】sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file

### ISSUE THREAD

**Issue by Valuebai** [CapAllen/Dashboard#2]
直接运行代码后，发现，无法打开sqlite数据库，麻烦大佬有时间帮忙看看

```
C:\python37\python.exe D:/codePython/Dashboard-master/run.py
Engine(sqlite:///Doc/FakeDatasets.db)
Traceback (most recent call last):
  File "C:\python37\lib\site-packages\sqlalchemy\engine\base.py", line 2345, in _wrap_pool_connect
    return fn()
  File "C:\python37\lib\site-packages\sqlalchemy\pool\base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "C:\python37\lib\site-packages\sqlalchemy\pool\base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\python37\lib\site-packages\sqlalchemy\pool\base.py", line 495, in checkout
    rec = pool._do_get()
  File "C:\python37\lib\site-packages\sqlalchemy\pool\impl.py", line 239, in _do_get
    return self._create_connection()
  File "C:\python37\lib\site-packages\sqlalchemy\pool\base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "C:\python37\lib\site-packages\sqlalchemy\pool\base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "C:\python37\lib\site-packages\sqlalchemy\pool\base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\python37\lib\site-packages\sqlalchemy\util\langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "C:\python37\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\python37\lib\site-packages\sqlalchemy\pool\base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "C:\python37\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\python37\lib\site-packages\sqlalchemy\engine\default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/codePython/Dashboard-master/run.py", line 29, in <module>
    df = get_data(test=True)
  File "D:\codePython\Dashboard-master\help_funcs.py", line 27, in get_data
    df_test = pd.read_sql_table(table_name='FakeDatasets',con=engine)
  File "C:\python37\lib\site-packages\pandas\io\sql.py", line 242, in read_sql_table
    meta.reflect(only=[table_name], views=True)
  File "C:\python37\lib\site-packages\sqlalchemy\sql\schema.py", line 4356, in reflect
    with bind.connect() as conn:
  File "C:\python37\lib\site-packages\sqlalchemy\engine\base.py", line 2272, in connect
    return self._connection_cls(self, **kwargs)
  File "C:\python37\lib\site-packages\sqlalchemy\engine\base.py", line 104, in __init__
    else engine.raw_connection()
  File "C:\python37\lib\site-packages\sqlalchemy\engine\base.py", line 2379, in raw_connection
    self.pool.unique_connection, _connection
  File "C:\python37\lib\site-packages\sqlalchemy\engine\base.py", line 2349, in _wrap_pool_connect
    e, dialect, self
  File "C:\python37\lib\site-packages\sqlalchemy\engine\base.py", line 1591, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\python37\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\python37\lib\site-packages\sqlalchemy\engine\base.py", line 2345, in _wrap_pool_connect
    return fn()
  File "C:\python37\lib\site-packages\sqlalchemy\pool\base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "C:\python37\lib\site-packages\sqlalchemy\pool\base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\python37\lib\site-packages\sqlalchemy\pool\base.py", line 495, in checkout
    rec = pool._do_get()
  File "C:\python37\lib\site-packages\sqlalchemy\pool\impl.py", line 239, in _do_get
    return self._create_connection()
  File "C:\python37\lib\site-packages\sqlalchemy\pool\base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "C:\python37\lib\site-packages\sqlalchemy\pool\base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "C:\python37\lib\site-packages\sqlalchemy\pool\base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\python37\lib\site-packages\sqlalchemy\util\langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "C:\python37\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\python37\lib\site-packages\sqlalchemy\pool\base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "C:\python37\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\python37\lib\site-packages\sqlalchemy\engine\default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/e3q8)

Process finished with exit code 1

```

**Comment by CapAllen** [comment]
你下载整个项目之后，直接运行`python run.py`就好了，你这里可能是因为路径问题导致的，只能先试试看。
> 参考：https://stackoverflow.com/questions/4636970/sqlite3-operationalerror-unable-to-open-database-file
